version: "2.2"
services:
  app:
    image: nginx:1.19
    ports:
      - "20080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/share/nginx/html:ro
    environment:
      TZ: Asia/Tokyo
